/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pruebas1;

public class Operaciones {
public  int Suma(int numeroUno, int numeroDos) {
		
		return numeroUno + numeroDos;
		// TODO Auto-generated method stub
		
		
	}

	public int agregoUno(int numeroUno) {
		// TODO Auto-generated method stub
		return ++numeroUno;
	}

	public int restaValorAbsoluto(int numeroUno, int numeroDos) {
	
		return Math.abs(numeroUno-numeroDos);
	}

	public int multiplicacion(int numeroUno, int numeroDos) {
	
		return numeroUno * numeroDos;
	}

	public int division(int numeroUno, int numeroDos) {
		// TODO Auto-generated method stub
		return numeroUno / numeroDos;
	}

	public String palabra(String palabraUno) {
		// TODO Auto-generated method stub
		return palabraUno;
	}

	public int contarPalabras(String palabraUno) {
		// TODO Auto-generated method stub
		return palabraUno.length();
	}

	public Boolean paroInpar(int numeroUno) {
	if (numeroUno < 5) {
		return false;
		
	}
		return true;
	}

	public boolean positivo(int numeroUno) {
		if (numeroUno > 0) {
			return true;
			
		}
		return false;
	}

	public boolean esverdadero(int numeroUno) {
		if ((numeroUno % 2)== 0) {
			return true;
			
		}else {
			return false;
		}
		
	}

	public int transformarPositivo(int numeroUno) {
		if (numeroUno > 0) {
			return numeroUno;
			
		}else {
		return numeroUno * -1;
		}
		
	}

	public boolean validacioAND(boolean operadorLogicoUno, boolean operadorLogicoDos) {
		if (operadorLogicoUno && operadorLogicoDos) {
			return true;
			
		}
		return false;
	}

	public boolean validacioOR(boolean operadorLogicoUno, boolean operadorLogicoDos) {
		if (operadorLogicoUno || operadorLogicoDos) {
			return true;
		}
		return false;
	}

	public String festividades(String colorUno, String colorDos) {
		if (colorUno == "verde" & colorDos == "naranja") {
			return "Halloween";			
		} else if (colorUno == "rojo" & colorDos == "naranja") {
			return "pascua";			
		}
		
		return "navidad";
	}

	public boolean validacionbooleanynumero(int numeroUno, int numeroDos) {
		if (numeroUno == 6 & numeroDos == 117) {
			return false;
			
		}
		return true;
	}
}
